// Gemini-backed suggestion generation: maps a student's selection + comment on
// the rendered HTML back to the Typst source in main.typ and proposes a minimal
// edit. The exact-match validation below is load-bearing: an original_snippet
// that doesn't appear exactly once in the source is rejected, which makes the
// fuzzy AI mapping deterministic and safe to apply later.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { GoogleGenAI, Type } from "@google/genai";
import { settings } from "./store.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const MAIN_TYP = path.resolve(__dirname, "..", "..", "main.typ");
const REQUESTED_MODEL = "gemini-3.5-flash-lite";

export function getApiKey() {
  return settings.geminiApiKey || process.env.GEMINI_API_KEY || null;
}

let resolvedModel = null;

// The requested model ID may not exist verbatim; prefer it if listed,
// otherwise fall back to the newest available flash-lite model.
async function resolveModel(client) {
  if (resolvedModel) return resolvedModel;
  try {
    const names = [];
    const pager = await client.models.list();
    for await (const m of pager) {
      names.push((m.name || "").replace(/^models\//, ""));
    }
    if (names.includes(REQUESTED_MODEL)) {
      resolvedModel = REQUESTED_MODEL;
    } else {
      const lite = names
        .filter((n) => n.includes("flash-lite") && !n.includes("preview") && !n.includes("exp"))
        .sort()
        .reverse();
      resolvedModel = lite[0] || REQUESTED_MODEL;
    }
  } catch {
    resolvedModel = REQUESTED_MODEL;
  }
  if (resolvedModel !== REQUESTED_MODEL) {
    console.log(`Gemini: '${REQUESTED_MODEL}' not available, using '${resolvedModel}'`);
  }
  return resolvedModel;
}

export function currentModel() {
  return resolvedModel || REQUESTED_MODEL;
}

const RESPONSE_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    found: { type: Type.BOOLEAN },
    original_snippet: { type: Type.STRING },
    replacement_snippet: { type: Type.STRING },
    rationale: { type: Type.STRING },
  },
  required: ["found", "original_snippet", "replacement_snippet", "rationale"],
};

const SYSTEM = `You are helping revise Typst course materials based on student feedback.

You are given the full Typst source of a course website, the text a student selected on the RENDERED page, and the student's comment.

Your job:
1. Find the exact contiguous region of the Typst source that produces the selected rendered text. Copy it byte-for-byte from the source — including punctuation, brackets, and indentation — because it will be applied with exact string replacement. Keep the snippet as small as possible while remaining unique in the file.
2. Write a replacement snippet that is valid Typst and changes only what the student's comment asks for. Do not reformat surrounding code.
3. Explain the change in one or two sentences in "rationale".

Notes on the source:
- Content is often data: arrays of tuples passed to functions like grade-breakdown() or key-dates(). Selected table text usually maps to a tuple field, not prose.
- Some rendered prose (e.g. the full policy sections) is generated by library code that is NOT in this file. If the selected text does not come from this source file, or you cannot confidently locate it, set found to false, leave both snippets empty, and say why in rationale.

Return only the JSON object.`;

export async function suggest({ page, anchor, commentText }) {
  const key = getApiKey();
  if (!key) return { error: "not_configured" };

  const source = fs.readFileSync(MAIN_TYP, "utf8");
  const client = new GoogleGenAI({ apiKey: key });
  const model = await resolveModel(client);

  const user = [
    `Page path: ${page}`,
    `Selected rendered text: ${JSON.stringify(anchor.selectedText ?? "")}`,
    `Rendered context before selection: ${JSON.stringify(anchor.prefix ?? "")}`,
    `Rendered context after selection: ${JSON.stringify(anchor.suffix ?? "")}`,
    ``,
    `Student comment: ${commentText}`,
  ].join("\n");

  const response = await client.models.generateContent({
    model,
    contents: `${SYSTEM}\n\n<typst_source>\n${source}\n</typst_source>\n\n${user}`,
    config: {
      responseMimeType: "application/json",
      responseSchema: RESPONSE_SCHEMA,
    },
  });

  let parsed;
  try {
    parsed = JSON.parse(response.text);
  } catch {
    return { error: "bad_ai_response" };
  }

  if (parsed.found) {
    const canonical = locateSnippet(source, parsed.original_snippet || "");
    if (!canonical || canonical === parsed.replacement_snippet) {
      console.log(
        "AI snippet rejected (no unique source match). Model returned:",
        JSON.stringify((parsed.original_snippet || "").slice(0, 200)),
      );
      return {
        found: false,
        rationale:
          parsed.rationale ||
          "The AI could not locate a unique source region for this selection.",
        model,
      };
    }
    // Use the source's own bytes as the snippet (the model may have re-wrapped
    // whitespace); the replacement stays as the model/student wrote it.
    parsed.original_snippet = canonical;
  }

  return {
    found: Boolean(parsed.found),
    originalSnippet: parsed.found ? parsed.original_snippet : "",
    replacementSnippet: parsed.found ? parsed.replacement_snippet : "",
    rationale: parsed.rationale || "",
    model,
  };
}

function escapeRegex(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Find the snippet in the source: exact match first, then whitespace-tolerant
// (models often re-wrap hard-wrapped prose). Returns the source's own bytes,
// or null when there is no match or the match is ambiguous.
function locateSnippet(source, snippet) {
  const exact = snippet ? source.indexOf(snippet) : -1;
  if (exact !== -1) {
    return source.indexOf(snippet, exact + 1) === -1 ? snippet : null;
  }
  const words = snippet.trim().split(/\s+/).filter(Boolean);
  if (!words.length) return null;
  let matches;
  try {
    matches = [...source.matchAll(new RegExp(words.map(escapeRegex).join("\\s+"), "g"))];
  } catch {
    return null;
  }
  return matches.length === 1 ? matches[0][0] : null;
}

// Re-validate a snippet at apply time (the source may have changed since the
// suggestion was generated).
export function readSource() {
  return fs.readFileSync(MAIN_TYP, "utf8");
}
